# Generated by Django 3.1.7 on 2021-10-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student1',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_college', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('degree_name', models.CharField(max_length=100)),
                ('internship_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=100)),
                ('student_phone', models.CharField(max_length=100)),
                ('student_address', models.CharField(max_length=100)),
                ('student_gender', models.CharField(max_length=10)),
                ('notes', models.TextField()),
                ('username', models.CharField(default='ele30', max_length=100)),
            ],
        ),
    ]
